### ISSUE TITLE
ci: diamond storage check exceeds API rate limit

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#876] opened 2024-01-18 21:45 UTC
There is the "Check For Diamond Storage Changes" [workflow](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/workflows/diamond-storage-check.yml) which checks that storage collisions on contracts upgrades are not introduced. 

Sometimes it throws the "API rate limit exceeded" error which should be fixed.

What should be done:
1. Fix the API rate limit error
2. Enable (i.e. revert this [PR](https://github.com/ubiquity/ubiquity-dollar/pull/878)) storage checks

https://github.com/ubiquity/ubiquity-dollar/actions/runs/7576286107/job/20634758710?pr=875

refer

![Screenshot from 2024-01-18 17-42-28](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/9f02528d-488c-457c-9f4c-6eb7ae7acc3a)

**Comment by molecula451** [comment] 2024-01-18 21:45
@pavlovcik @rndquu @gitcoindev

**Comment by gitcoindev** [comment] 2024-01-19 07:15
@molecula451 @pavlovcik @rndquu 

I see a few ways to tackle this: 

1) Throw money at the problem and increase API rate limit to 15000 (may workaround the issue only short term).
2) Wait with next request until after the time specified by the x-ratelimit-reset header, the workflow would have to check this before running and wait in a loop, or we could have another workflow which would collect those errors and try to re-run. See https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#checking-the-status-of-your-rate-limit

But, the best would be to collect statistics and figure out which action eats up API rate the most and try to optimize it.

**Comment by rndquu** [comment] 2024-01-19 07:17
> But, the best would be to collect statistics and figure out which action eats up API rate the most and try to optimize it.

Or run the diamond storage check workflow only for modified contracts and not for all of them

**Comment by gitcoindev** [comment] 2024-01-19 07:18
> > But, the best would be to collect statistics and figure out which action eats up API rate the most and try to optimize it.
> 
> Or run the diamond storage check workflow only for modified contracts and not for all of them

Yes, let's open a ticket for that, this is very likely the root cause.

**Comment by molecula451** [comment] 2024-01-19 07:19
> Or run the diamond storage check workflow only for modified contracts and not for all of them

This one sounds like it will take time, for deployment, testing and we are in the middle of the judging, i think we need a fix asap

**Comment by rndquu** [comment] 2024-01-19 07:25
> > Or run the diamond storage check workflow only for modified contracts and not for all of them
> 
> This one sounds like it will take time, for deployment, testing and we are in the middle of the judging, i think we need a fix asap

Contracts are not deployed yet so there is no need for a fix asap unless I'm missing smth

**Comment by molecula451** [comment] 2024-01-19 07:27
the thing is that we are opening PRs and we are not visualizing what changes what on the storage as we originally did it with the workflow, unless we rely on manually handling as of now

**Comment by rndquu** [comment] 2024-01-19 07:29
> the thing is that we are opening PRs and we are not visualizing what changes what on the storage as we originally did it with the workflow, unless we rely on manually handling as of now

Why do we need to visualize the changes? The contracts are not deployed, we won't break anything.

**Comment by molecula451** [comment] 2024-01-19 07:41
good for now, it was better to clear things

**Comment by gitcoindev** [comment] 2024-01-19 08:00
@molecula451 @rndquu temporarily disabled storage changes but it may be that code QL analysis is the root cause.
I will also disable this temporarily and let's see if it helps.

https://github.com/ubiquity/ubiquity-dollar/pull/878

**Comment by molecula451** [comment] 2024-01-24 08:28
any updates in a solution for this one? @gitcoindev

**Comment by gitcoindev** [comment] 2024-01-24 09:20
> any updates in a solution for this one? @gitcoindev

hi @molecula451 , I am on it today, will try to come up with a solution ( or at least find a workaround).

**Comment by gitcoindev** [comment] 2024-01-24 10:27
Reopening, I merged to my fork to execute QA and bot closed the issue. QA is done and looks good, I will open a pull request now.

**Closed as completed** 2024-01-24 11:42 UTC
