### ISSUE TITLE
Enforce Conventional Commits

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#344] opened 2022-11-25 21:41 UTC
The following is commented away in our README but we never implemented this feature. It is a great way to standardize commit messages as well as to produce a great standardized input for automation tools, which for example, can automatically produce change logs for every deployment.

> 1. We [automatically enforce](https://github.com/conventional-changelog/commitlint) the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) format for commit messages. This can be frustrating for junior developers, but I promise that you'll quickly get used to it! -->

> The Conventional Commits specification is a lightweight convention on top of commit messages. It provides an easy set of rules for creating an explicit commit history; which makes it easier to write automated tools on top of. -->

**Comment by rndquu** [comment] 2022-11-30 12:08
hey, you can assign this task to me

as far as I understand every commit message should be checked if it is written in "conventional commit style"

**Comment by 0x4007** [comment] 2022-11-30 16:47
This bounty is for enforcing it with a precommit hook. As long as you can make it work with a hook you're authorized. Let me know.

**Comment by rndquu** [comment] 2022-12-15 12:31
@pavlovcik 

wallet: 0x336C033842FA316d470e820c81b742e62A0765DC

pls also check this weird thing https://github.com/ubiquity/ubiquity-dollar/pull/378#issuecomment-1352988358

**Comment by sergfeldman** [comment] 2022-12-15 15:15
> @pavlovcik
> 
> wallet: 0x336C033842FA316d470e820c81b742e62A0765DC
> 
> pls also check this weird thing [#378 (comment)](https://github.com/ubiquity/ubiquity-dollar/pull/378#issuecomment-1352988358)

@pavlovcik The PR is merged, the issue is closed, but there is a question regarding "this weird thing ^"
Should I perform the payment?

**Comment by 0x4007** [comment] 2022-12-17 18:23
There's a small issue with the last commit where lint-staged should be enabled (@rndquu please fix) then we can release payment.

This week I tried auto-merging to be a little more hands off but seems like that introduces some new issues which we just observed now.

**Comment by 0x4007** [comment] 2022-12-17 23:04
Issue is resolved!

> 0x336C033842FA316d470e820c81b742e62A0765DC

https://etherscan.io/tx/0x93fd0fbe4e05ff9c8c5984c818c755b4e379bbd55aa953dff9147347796a5ca9

**Closed as completed** 2022-12-19 21:31 UTC
Labels: DevOps
